### ISSUE TITLE
train / test sample size

### ISSUE THREAD

**Issue by fyzl233** [neolifer/LLM4POI#3]
Your preprocessing code seems to be different from STHGCN. What is the sample size for your training and testing after preprocessing?

After run I get

nyc： 
train set: 11022 trajectory , test set: 1447 trajectory 
tky:
train set: 51661 trajectory  , test set: 7079 trajectory 
ca:
train set: 36374 trajectory  , test set: 2864 trajectory 

Is it right? Thanks for your reading~

**Comment by neolifer** [comment]
Hi, thank you for your interest.

The preprocessing code for getting the samples is based on the code in STHGCN. 

What we changed: 
1. we fixed some bugs.
2. we removed the part to generate the hypergraph.
3. we added back the removed entries to the test set. The original code only keeps the last entry in a trajectory because the trajectory is already used to generate the hypergraph.
4. we kept the first entry in every trajectory.

So, what we get should be the complete data after filtering and splitting.
The sample size we have is the same as what you get.
